#!/usr/bin/env bash

cd /app/quiz/
uv run manage.py migrate
uv run gunicorn --bind '0.0.0.0:8000' --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread --log-file=- quiz.wsgi:application
