#!/usr/bin/env sh

cd /app/quiz/

if [ ! -f "/data/db.sqlite3" ]; then
  echo "[WARNING] Database not found"
  # if [ -f "/app/quiz/sample.db" ]; then
  #   echo "[INFO] Copying a sample db."
  #   cp /app/quiz/sample.db /data/db.sqlite3
  # fi
fi

uv run manage.py migrate
uv run gunicorn --bind '0.0.0.0:8000' --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread --log-file=- quiz.wsgi:application
