#!/usr/bin/env bash

# First arg sets text style. Second arg sets sets foreground or background color.
# 0 (reset/normal) / 1 (bold) / 2 (dim) / 3 (italic) / 4 (underline)
# foreground = 30s or background = 40s
color_text() {
  echo -e "\033[$1;$2m$3\033[0m"
}

color_text 1 32 "Running tests for the app quizAPI"
uv run quiz/manage.py test quizAPI --settings=quiz.settings.tests

echo -e "\n\n"

color_text 1 32 "Running tests for the app quizAUTH"
uv run quiz/manage.py test quizAUTH --settings=quiz.settings.tests
