# Generated by Django 5.2.1 on 2025-07-04 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.TextField(max_length=500)),
                ("back", models.TextField(max_length=5000)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("Flashcard", "Flashcard"),
                            ("Matchcard", "Matchcard"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "Quiz Details",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="quizAPI.card"
                    ),
                ),
                (
                    "quiz_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quizAPI.quizdetails",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "unique_together": {("quiz_id", "card_id")},
            },
        ),
    ]
