# Generated by Django 5.2.1 on 2025-06-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizAPI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.CharField(max_length=100)),
                ("back", models.CharField(max_length=100)),
                (
                    "card_type",
                    models.CharField(
                        choices=[("Flash Card", "Fc"), ("Match Card", "Mc")],
                        default="Flash Card",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizAPI.card"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="Flashcard",
        ),
        migrations.AddField(
            model_name="quiz",
            name="quiz_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="quizAPI.quizdetails"
            ),
        ),
    ]
