# Generated by Django 5.2.1 on 2025-07-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="card_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quizAPI.card"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="quiz_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quizAPI.quizdetails"
            ),
        ),
    ]
