# Generated by Django 5.2.1 on 2025-06-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizAPI", "0002_card_quiz_quizdetails_delete_flashcard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_type",
            field=models.CharField(
                choices=[("FC", "Flashcard"), ("MC", "Matchcard")],
                default="FC",
                max_length=10,
            ),
        ),
    ]
