# Generated by Django 5.2.1 on 2025-06-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizAPI", "0003_alter_card_card_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_type",
            field=models.CharField(
                choices=[("FC", "Flashcard"), ("MC", "Matchcard")],
                default="FC",
                max_length=2,
            ),
        ),
    ]
