# Generated by Django 5.2.1 on 2025-06-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizAPI", "0004_alter_card_card_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_type",
            field=models.CharField(
                choices=[("Flashcard", "Flashcard"), ("Matchcard", "Matchcard")],
                max_length=15,
            ),
        ),
    ]
