# Generated by Django 5.2.1 on 2025-06-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizAPI", "0005_alter_card_card_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="quiz_info",
            new_name="quiz",
        ),
    ]
