# Generated by Django 5.2.1 on 2025-06-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizAPI", "0006_rename_quiz_info_quiz_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="back",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="card",
            name="front",
            field=models.CharField(max_length=500),
        ),
    ]
