name: Docker Image CI

on:
  push:
    branches: [ "release" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Extract release version
        id: get_version
        run: |
          # Assumes the release version is in a file called VERSION
          if [ -f VERSION ]; then
            VERSION=$(cat VERSION)
          else
            # Fallback: use short SHA
            VERSION=${GITHUB_SHA::7}
          fi
          echo "release_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend Docker image
        run: |
          docker build . \
            --file docker/backend/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/quiz-backend:${{ steps.get_version.outputs.release_version }}

      - name: Build frontend Docker image
        run: |
          docker build . \
            --file docker/frontend/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/quiz-frontend:${{ steps.get_version.outputs.release_version }}

      - name: Push backend Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quiz-backend:${{ steps.get_version.outputs.release_version }}

      - name: Push frontend Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quiz-frontend:${{ steps.get_version.outputs.release_version }}
